config/routes.rb
Rails.application.routes.draw do
  root to: 'plans#index'
  resources :plans, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :purpose
  belongs_to :who
  belongs_to :spot

  validates :name, presence: true

  validates :purpose_id, :who_id, :spot_id, numericality: { other_than: 1, message: "can't be blank" } 
end

app/models/purpose.rb
class Purpose < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'リラックス' },
    { id: 3, name: 'アクティブ' },
    { id: 4, name: '指定なし' }
  ]

  include ActiveHash::Associations
  has_many :plans
  end

app/models/spot.rb
class Spot < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '浜松・浜名湖' },
    { id: 3, name: '掛川・島田・大井川' },
    { id: 4, name: '藤枝・焼津・用宗' },
    { id: 5, name: 'オクシズ' },
    { id: 6, name: '静岡・清水' },
    { id: 7, name: '富士・富士宮' },
    { id: 8, name: '沼津・三島' },
    { id: 9, name: '熱海・伊東' },
    { id: 10, name: '中伊豆' },
    { id: 11, name: '東伊豆' },
    { id: 12, name: '伊豆高原' },
    { id: 13, name: '下田・南伊豆' },
    { id: 14, name: '西伊豆' }
  ]

  include ActiveHash::Associations
  has_many :plans
  end

app/models/who.rb
class Who < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '家族と' },
    { id: 3, name: '恋人と' },
    { id: 4, name: '仲間と' },
    { id: 5, name: '一人で' },
    { id: 6, name: '指定なし' }
  ]

  include ActiveHash::Associations
  has_many :plans
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.order("created_at DESC")
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def plan_params
    params.require(:plan).permit(:name,:purpose_id,:who_id,:spot_id,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shizutri2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/index.html.erb
<h1>計画一覧</h1>
<%= link_to "投稿する", new_plan_path, method: :get, class:"post" %>

<% @plans.each do |plan| %>
  <div class="plan">
    <div class="plan-name">
      <%= plan.name %>
    </div>
    <div class="plan-purpose">
      <%= plan.purpose.name %>
    </div>
    <div class="plan-who">
      <%= plan.who.name %>
    </div>
    <div class="plan-spot">
      <%= plan.spot.name %>
    </div>
    <div class="plan-introduction">
      <%= plan.introduction %>
    </div>
  </div>
<% end %>

app/views/plans/new.html.erb
<%= form_with model: @plan, url:plans_path, local: true do |f| %>
  <div class="plan-box">
    記事を投稿する
    <%= f.text_field :name, class:"name", placeholder:"タイトル" %>
    <%= f.text_area :introduction, class:"introduction", placeholder:"テキスト" %>
    <%= f.collection_select(:purpose_id, Purpose.all, :id, :name, {}, {class:"purpose-select"}) %>
    <%= f.collection_select(:who_id, Who.all, :id, :name, {}, {class:"who-select"}) %>
    <%= f.collection_select(:spot_id, Spot.all, :id, :name, {}, {class:"spot-select"}) %>
    <%= f.submit "投稿する" ,class:"btn" %>
  </div>
<% end %>